### ISSUE TITLE
RFE: implemt flex/bison based ini file parser

### ISSUE THREAD

**Issue by kloczek** [gssapi/gssproxy#3]
Currently gssproxy uses libini_config to parse its configuration file.
That library is using libbasicobjects, libcollection, libpath_utils and libref_array libraries. All this to parse only few tockens.

As gssproxy is kind core distribution package I think that would be way better to rewrite that part using bison/flex to reduce size of the minimal system. As good starting pont could be probably used https://github.com/ezaquarii/bison-flex-cpp-example.

**Comment by simo5** [comment]
@kloczek 
Are you volunteering to propose a rewrite like that that will maintain complete compatibility ?

**Comment by kloczek** [comment]
First I want to see your opinion because implementing anythiong in case if you will reject even idea would be pointless.

**Comment by simo5** [comment]
In the past we used iniconfig (or some such named package) because it was simpler, but it was also very buggy.

Since then we moved to ding libs to handle config because in most cases they were already available on the system anyway where we got installed (sssd also has them as dependency) and we wanted a library that would handle multiple configuration sections correctly, as well as handling properly string, vs list, vs numbers, etc...

I am not particularly concerned about the fact that package is split in 4 libraries, so I also do not see the urgency of replacing it with something custom grown.

I would, nonetheless consider a replacement if there was a downstream OS that actually had an issue with the dependency and there was a contribution that added good quality parsing. I would definitely not accept WIP code or low quality parsing.

**Comment by frozencemetery** [comment]
Please rethink your approach to minimization.

Removing our use of an INI parser does not mean we stop using INI.  It means that gssproxy would then contain an entire INI parser - as would every other application that uses INI.  This is a slippery slope to a staticly linked distro, which is *not* minimal.

To restate:r educing dependency chains is not the same as making the system smaller, or less complex.  Removing our use of an external parser doesn't mean we get to stop using INI - it just makes the gssproxy package bigger by the size of the INI parser.  Time would be better spent on reducing the overhead in packages rather than the number of packages present.

If someone showed up with a library for a better INI parser than what ding-libs gives us, I'd be interested, but I have looked for them and as far as I can tell they do not exist.  If you wanted to make a better INI parser, I would be interested - but it would have its own repository.

**Comment by simo5** [comment]
Alright, seem that Robbie gave a very good answer why we should not be interested in just an implementation in our repo.
So I am going to close this issue.
However if really there is a better (and we'll discuss then what 'better' means) library we can depend on, and issue or PR can be opened.
