### ISSUE TITLE
Unified config file is processed despite error messages

### ISSUE THREAD

**Issue by lechner** [gssapi/gssproxy#31]
Hi,

I switched to `gssproxy` recently—after years of relying on `rpc.svcgssd`. My installation on Debian _bullseye_ came with a unified configuration file in `/etc/gssproxy/gssproxy.conf`, but my logs are being spammed with these messages:
```
Error when reading config directory: File /etc/gssproxy/gssproxy.conf did not match provided patterns. Skipping.
Error when reading config directory: File /etc/gssproxy/gssproxy.conf~ did not match provided patterns. Skipping.
```
The messages are not correct. The regular file (although perhaps not the backup) is being read and processed!

I believe it is the result of the call [here](https://github.com/gssapi/gssproxy/blob/main/src/gp_config.c#L815-L830).

Maybe unified config files are superseded, but the documentation [still recommends them](https://github.com/gssapi/gssproxy/tree/main/docs#configuring-gssproxy). Which should I use, please?

Also, should `gssproxy` ignore editor backup files? Thank you!

Kind regards
Felix Lechner

**Comment by simo5** [comment]
We use /etc/gssproxy/gssproxy.conf on Fedora as well, and I do not see those logs, so will need to investigate, any file that is not part of the pattern should just be skipped afaik.

**Comment by frozencemetery** [comment]
This is an old ding-libs bug: https://pagure.io/SSSD/ding-libs/issue/3182

Specifically, Debian's ding-libs is missing this commit: https://pagure.io/SSSD/ding-libs/c/be9ca3a2c26b061d1f22bd4a09009bba7a01f67b .  Presumably this is because it hasn't landed in a release yet - ding-libs last released a month prior in 2017 (there have been 16 commits since then).

So there's nothing we can do in gssproxy, unfortunately - it's on the ding-libs maintainers (upstream and/or in Debian) to resolve.

**Comment by lechner** [comment]
Thanks for the quick response! I amended and retitled [Debian Bug#950514](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=950514).

It might be helpful to lean on `ding-libs` upstream to tag a new release, if you have any pull there. Thanks!

**Comment by frozencemetery** [comment]
I opened a bug with them https://pagure.io/SSSD/ding-libs/issue/3190 ; we'll see if anything comes of it, I guess.
